services:
  server:
    build:
      context: ./src/server
    container_name: red_tetris_server
    env_file:
        - .env
    volumes:
    - ./src/server:/app/server
    healthcheck:
      test: ["CMD"]
      interval: 5s
      timeout: 3s
      retries: 2

  client:
    build:
        context: ./src/client
    container_name: red_tetris_client
    volumes:
    - ./src/client:/app/client
    depends_on:
        server:
            condition: service_healthy
    ports:
    - "1700:1700"